# MLflow Configuration


tracking_uri: "https://dagshub.com/7a99ui/premier_league_mlops.mlflow"
registry_uri: "https://dagshub.com/7a99ui/premier_league_mlops.mlflow"

experiment_name: "premier-league-prediction"

autolog: true

dagshub:
  enabled: true
  repo_owner: "7a99ui"
  repo_name: "premier_league_mlops"

# Artifacts
artifact_location: "mlartifacts"

